//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem.model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class QestionAnswer
    {
        public string Ans_body { get; set; }
        public int Q_Id { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
