//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem.model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Exam_Question
    {
        public int Q_Id { get; set; }
        public int Exam_Id { get; set; }
        public Nullable<int> St_Id { get; set; }
        public string Stud_Ans { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
    }
}
